# Generated by Django 4.1.7 on 2023-03-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Nombre')),
            ],
        ),
    ]
